### ISSUE TITLE
org.postgresql.util.PSQLException: This ResultSet is closed.

### ISSUE THREAD

**Issue by ashishsoni** [randerzander/docker-hdp#19]
Getting below error when starting Hive Meta Store 	

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:233)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
NestedThrowablesStackTrace:
org.postgresql.util.PSQLException: This ResultSet is closed.
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2
ResultSet.java:2656)
	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc

**Comment by EvgenAnufriev** [comment]
@ashishsoni , I'm  facing the same issue. Are you using the single-container.yml?

**Comment by ashishsoni** [comment]
@EvgenAnufriev Use Postgresh 9.4 docker image instead of latest as latest is postgres 10 version which is not supported by Ambari and HDP , Once i changed it worked for me . 
You have to modify postgresh docker file to say FROM postgres:9.4 and it should work

**Comment by EvgenAnufriev** [comment]
@ashishsoni , THANKS!!!!! 
If you have time, can you tell, how you found what causes error?

**Comment by ashishsoni** [comment]
@EvgenAnufriev  i did not found the cause but i checked the HDP docs and it says not supported PG 10 so i just straight went to lower pg version, will try to find out if i get some time.

**Comment by EvgenAnufriev** [comment]
Btw, Even though i've changed  hdp repo version to 2.6.3 in every place i found, I see links to 2.6.4 in "Stack and Versions" instead. @ashishsoni,  maybe you have any idea why? what did i miss?
